### ISSUE TITLE
feature proposal: insert

### ISSUE THREAD

**Issue by billiegoose** [mleko/typescript-array-utils#1]
Hi,
I have probably looked at a dozen modules on npm for variants of "immutable" "array" "helper" "util" and yours is the only module that fits my bill. However I think I will need to add an `insert` method. Are you actively maintaining this module? If so, can I submit a PR that adds an `insert` method? Thanks in advance for taking time to read this!

**Comment by mleko** [comment]
Sure you can submit PR.
I really appreciate any help you can provide.

**Comment by billiegoose** [comment]
done!
